ame: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: vulnerable
      run: sudo chmod +x ./bash/*.sh && sudo ./bash/heartbleed-vulnerable-server.sh
    - name: pentest
      run: sudo chmod +x ./bash/*.sh && sudo ./bash/heartbleed-vulnerable-pentest.sh
#     - name: Test
#       run: sudo mono main.exe
