name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: makedir
      run: sudo mkdir -p /home/etudiant

    # - name: check user
    #   run: whoami


    - name: dockerinstall chmod
      run: chmod +x ./bash/install-docker.sh

      
    - name: dockerinstall test
      run: ./bash/install-docker.sh

    - name: vulnerable preparing
      run: | 
       sudo apt-get update -y && sudo apt-get install -y python docker-compose
       docker pull andrewmichaelsmith/docker-heartbleed
      #  git clone https://github.com/injcristianrojas/heartbleed-example.git
      #  cd heartbleed-example
      #  sudo docker-compose up &
      #  docker run -d andrewmichaelsmith/docker-heartbleed

    - name: vulnerable chmod
      run: sudo chmod +x ./bash/heartbleed-vulnerable-server.sh 


    - name: vulnerable
      run: sudo ./bash/heartbleed-vulnerable-server.sh


    - name: docker image
      run: sudo docker image ls    
      
      
    - name: pentest chmod
      run: sudo chmod +x ./bash/heartbleed-vulnerable-pentest.sh
    - name: pentest after 5 min
      run: sleep 500 && sudo ./bash/heartbleed-vulnerable-pentest.sh
#     - name: Test
#       run: sudo mono main.exe
